s = set()

n = input("Enter num : ")
s.add(int(n))
n = input("Enter num : ")
s.add(int(n))
n = input("Enter num : ")
s.add(int(n))
n = input("Enter num : ")
s.add(int(n))
n = input("Enter num : ")
s.add(int(n))
n = input("Enter num : ")
s.add(int(n))
n = input("Enter num : ")
s.add(int(n))
n = input("Enter num : ")
s.add(int(n))

print(s)